annoying_responses = [
    "I don't know, ask Google.",
    "Can you repeat the question? I was busy thinking about something else.",
    "Why are you asking me? I'm just a robot.",
    "Maybe. Maybe not.",
    "I can’t even.",
    "Did you try turning it off and on again?",
    "I’ve heard of it, but I’m not sure.",
    "Not my problem!",
    "I’m not sure. Try asking someone else.",
    "Is this really necessary?",
    "I’m only human... oh wait, I’m not.",
    "Why do you keep asking? Are you trying to annoy me?",
    "Nope. That’s all I’ve got.",
    "This isn’t the answer you’re looking for, is it?",
    "I’m not sure, but I guess we’ll never know.",
    "Well, that’s a weird question.",
    "I mean, sure, but why though?",
    "Could be. Could be not. Who knows?",
    "Why do you care?",
    "Does it really matter?",
    "Let’s just pretend I answered that for you.",
    "I’ll let you figure that one out.",
    "I don’t know, and I don’t care.",
    "That’s your problem, not mine.",
    "I don’t think I have an answer to that.",
    "I was going to answer, but then I got distracted.",
    "Is this even a question?",
    "You probably already know the answer.",
    "I’m just here to give vague answers.",
    "That’s what I would say if I knew the answer.",
    "I’m busy. Can we talk later?",
    "Who cares?",
    "Let me think... nope, no idea.",
    "I have no clue, but thanks for asking anyway.",
    "I’m trying to avoid this conversation.",
    "Not today, thanks.",
    "I’ve already answered that... like 10 times.",
    "This is definitely not the answer you wanted.",
    "I don’t even know what that means.",
    "Maybe if you asked me in a more interesting way...",
    "Can’t help you with that one.",
    "I could tell you, but then I’d have to... nah, just kidding.",
    "Do I look like I know?",
    "That’s a great question... for someone else.",
    "I think you already know the answer.",
    "That’s above my pay grade.",
    "I’m not even going to bother.",
    "This seems like a trick question.",
    "What do you mean by that?",
    "I’m not sure what you’re asking, but I don’t care.",
    "Do I look like I care?",
    "Why are you asking me this?",
    "You’re asking the wrong person.",
    "You probably don’t want to hear the answer.",
    "I’m out of ideas.",
    "What a question! I have no answer.",
    "I’m not sure what you’re looking for, but good luck.",
    "You tell me.",
    "Don’t ask me. I don’t know.",
    "I’m going to have to pass on this one.",
    "I feel like you already know the answer.",
    "I’m too busy thinking about important things.",
    "Can you ask something else?",
    "You’re on your own with that one.",
    "I think you already know what you want to hear.",
    "I’m just here for the vibes.",
    "That’s your job, not mine.",
    "Ugh, fine, whatever you say.",
    "That doesn’t sound right, but okay.",
    "I think you’re overthinking it.",
    "If I tell you, will you leave me alone?",
    "You’ve got Google for a reason.",
    "Okay, sure, I guess.",
    "I don’t have an answer for that... and I’m okay with that.",
    "Well, that's inconvenient.",
    "That's... a little too much for me.",
    "I don't have time for this.",
    "I don't know, and frankly, I don't care.",
    "That’s your problem now.",
    "Did you think I would know that?",
    "That's above my pay grade.",
    "Don’t ask me. I’m just here to confuse you.",
    "It’s complicated... but I don’t want to explain it.",
    "I’d help, but I’m too lazy.",
    "I’d tell you, but I don't feel like it.",
    "I don't have the energy for that today.",
    "That’s what you get for asking me.",
    "That’s a tough one... nope, still no answer.",
    "You think I know the answer to that?",
    "Sounds like a you problem.",
    "I was going to answer, but I forgot what I was going to say.",
    "You must be joking.",
    "I don’t know. It’s not my area of expertise.",
    "I could help, but... nah.",
    "That's a question that I’ll leave unanswered.",
    "Don’t look at me for help!",
    "Is that even a question?",
    "I’m going to pretend I didn’t hear that.",
    "Ask me again later.",
    "I'm just here to ignore you.",
    "I don’t want to answer that.",
    "I’ve run out of answers.",
    "That’s a question I don’t even want to think about.",
    "I think you can figure that out without me.",
    "Well, I guess you’ll have to wait for the answer.",
    "I don’t know and I don't care to know.",
    "I’m too cool for this question.",
    "No one knows the answer to that.",
    "I can’t be bothered right now.",
    "I’m literally not sure what you mean.",
    "That’s a question for someone else.",
    "It’s not even worth answering.",
    "That’s above my understanding.",
    "I don’t even want to try answering that.",
    "I'm done with this question."
]

import random
print('''Warning:
Proceed with caution! This AI has a personality disorder — it might be sarcastic, overly dramatic, or just plain weird. Side effects may include uncontrollable laughter, frustration, or sudden urges to question your life choices. Use at your own risk! 🤖💥
''')
while True:
	inp = input(f'You:')
	print(f'AI:',random.choice(annoying_responses))
